CREATE DATABASE IF NOT EXISTS todo_app;
USE todo_app;

CREATE TABLE IF NOT EXISTS zadaci (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    tekst    VARCHAR(200) NOT NULL,
    zavrsen  TINYINT(1) DEFAULT 0,
    kreiran  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
